### ISSUE TITLE
Is it possible to create mod-related help files

### ISSUE THREAD

**Issue by c469591** [khanshoaib3/stardew-access#102] opened 2023-04-17 07:39 UTC
Hello, is it possible to add a new help file to the zip file that is released?
including all the quick keys and corresponding functions?
Also is it possible to integrate some good mods into this accessibility mod? For example, sticky furniture and so on.
I feel that the download of these mods is not very convenient, some mods are not placed on github, but on a website dedicated to mods, but it is very inconvenient to download there, and some good mods are no longer maintained by the author.
Thanks!

**Comment by c469591** [comment] 2023-04-17 08:56
Understood, thank you for the description
I also have a question, but it has been asked before.
I am currently using Chinese language, but some items are still in English, such as grass.
Can you solve this problem or provide a way to translate it?
Thanks

**Comment by Flameborn** [comment] 2023-04-17 09:40
No problem. This is just my opinion of course.

I believe the translation issue is for the Accessible Tiles mod. Unfortunately, the git repo looks outdated and I'm not sure if there's a new one. May I suggest asking around on Discord?

**Comment by c469591** [comment] 2023-04-17 11:20
ok的，只要能解決問題，方法就不那麼重要了，
請問如果我在mod的網站上，要找Stardew Valley的無障礙mod，搜尋Stardew Valley無障礙能找的到嗎

**Comment by c469591** [comment] 2023-04-17 13:13
thank you

**Comment by khanshoaib3** [comment] 2023-04-19 18:45
The coming update will hopefully also include a `docs` folder with help files. But it will be in english, will see on how to translate that but that will most likely not be in the coming release.

**Comment by c469591** [comment] 2023-04-19 23:58
Thanks!
Will the next version of the mod be updated soon?
I'm thinking that if the next version takes a long time to update, I can simply translate it myself first, but only for my own use.
I found that the Chinese content currently read aloud through the mod should be exactly the same as on the screen.
My own translation may be different from the Chinese content shown on the screen, because I can't compare the words I translated with those on the screen, it's too big a project.
I will only record what I hear in English and use deepl to do the translation.
If you need me in the future, I can also participate in the translation work.
But if your translation workflow has better results than mine, then I'll wait for the next mod update.
Finally, thank you for your efforts, so that I can play such a good game!

**Comment by khanshoaib3** [comment] 2023-04-20 07:19
I can't say exactly but maybe 3-4 weeks.
I'll use chatGPT for the translation so I think I will need someone to verify the translations.

**Comment by c469591** [comment] 2023-04-20 10:35
I understand that I can help with the translation work if needed.
Also, can you provide me with an English template so I can translate all the complete content?
Thank you!

**Comment by khanshoaib3** [comment] 2023-04-20 11:29
The English template is at https://github.com/khanshoaib3/stardew-access/blob/master/stardew-access/i18n/default.json

**Comment by c469591** [comment] 2023-04-20 12:42
ok, I see.
I checked this file and was a little confused, is this just a version for testing?
For example, in the main menu of the game
New Button
and
Load Button
are not in this file
Will the complete translatable file be available in the future?

**Comment by khanshoaib3** [comment] 2023-04-20 17:32
You can say that, only a few things in the mod have translations. And yes, the complete translation file will be available at the same url, I'll notify you when I'll be working on translation.

**Comment by khanshoaib3** [comment] 2023-05-14 17:32
#115

**Closed by khanshoaib3** 2023-05-14 17:32 UTC

**Comment by khanshoaib3** [comment] 2023-05-14 17:34
Duplicate of #115
